---
# https://yamllint.readthedocs.io/en/stable/
# yamllint --strict -c .github/linters/.yaml-lint.yml .
extends: default

# skip everything ignored by .gitignore
ignore: |
  /vendor/

rules:
  document-start: disable
  line-length: disable
  truthy: false
  comments:
    min-spaces-from-content: 1
